development:
  adapter: mysql2
  encoding: utf8
  database: bk_tutor_dev
  username: root
  password: "123456"
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: bk_tutor_test
  username: root
  password: "123456"
  host: 127.0.0.1